Repository DecodersCommunity/expense-tracker-vanilla, pull requests merged in 2022-10, with the labels that each got.

#3 input type fixed
  main/index.html
Labels: hactoberfest, hacktoberfest-accepted

#4 Did some styling and made website responsive.
  main/index.html
  main/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#10 Center the element of the row of the table
  main/index.js
  main/style.css
Labels: hacktoberfest-accepted
